version: '3.8'

services:
  nginx:
    image: nginx:1.27.4-alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/code:delegated
      - ./nginx.conf:/etc/nginx/nginx.conf
    working_dir: /code

  php:
    build: .
    volumes:
      - ./:/code:delegated
      - ./opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
      - ./public/uploads:/var/www/html/public/uploads
      - ./storage:/code/storage
      - ./bootstrap/cache:/code/bootstrap/cache
    environment:
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - data:/var/lib/mysql
      - ./mysql.cnf:/etc/mysql/conf.d/custom.cnf

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8081:80"

volumes:
  data:

